data_root= '../dataset/TUSimple' # Need to be modified before running
epoch= 100
batch_size= 8
optimizer= 'SGD'
learning_rate= 0.0005
weight_decay= 0.0001
momentum= 0.9
scheduler= 'multi'
steps= [50,75]
gamma= 0.1
warmup= 'linear'
warmup_iters= 100
backbone= 'erfnet'
weight_cls = [1, 182, 153, 136, 189]
note= ''
log_path= ''
finetune= 'pretrained/model_best.pth'
resume= None
test_model= ''
test_work_dir= ''
num_lanes= 4
var_loss_power= 2.0
auto_backup= True
crop_ratio = 1
train_width= 640
train_height= 360
fc_norm= False
soft_loss= True
eval_mode= 'normal'
